import type { Metadata } from "next";
import Navbar from "./Components/Navbar/page";
import Footer from "./Components/Footer/page";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
        >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
